version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: ContainerMySql
    environment:
      MYSQL_DATABASE: 'Animix'
      MYSQL_PASSWORD: 'urubu100'
      MYSQL_ROOT_PASSWORD: 'urubu100'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    jre-default:
      image: openjdk-11-jre
      build:
      context: . 
      dockerfile: dockerfile
      container_name: ContainerAnimixMySql